### ISSUE TITLE
[Bug] 切换至默认主题色没反应

### ISSUE THREAD

**Issue by Wesley-Young** [Stapxs/Stapxs-QQ-Lite-Theme#2]
<img width="952" alt="image" src="https://github.com/user-attachments/assets/5bc0a840-d091-4d4d-98cf-aa52bf3d26fe">
如图，切换至默认主题色（林槐蓝）时页面颜色不发生变化，只有切换至别的颜色时才会变化至对应颜色。

**Comment by Stapxs** [comment]
嗯……默认主题的 id 是 0 被一个蹩脚的 if 给拦住了 😭
等待发版
