### ISSUE TITLE
[Bug] 窗体过宽时页面布局紊乱

### ISSUE THREAD

**Issue by Wesley-Young** [Stapxs/Stapxs-QQ-Lite-Theme#3]
## Before
<img width="610" alt="image" src="https://github.com/user-attachments/assets/86d69df2-9fe3-41a2-afc1-3b8094515565">

## After
<img width="846" alt="image" src="https://github.com/user-attachments/assets/e7a3768f-190a-43f0-901e-4470b98ab966">

如图所示，当窗体宽度超过某一值后，头像与群昵称、消息框等内容重叠。

**Comment by Stapxs** [comment]
一个不知道为什么写在那边的 margin-left 导致的（x
等待发版
