### ISSUE TITLE
[Bug] 页面左下角 “更多” 进入二级菜单后，原先的一级菜单显示不正常

### ISSUE THREAD

**Issue by Wesley-Young** [Stapxs/Stapxs-QQ-Lite-Theme#4]
<img width="242" alt="image" src="https://github.com/user-attachments/assets/720d956c-4c6e-412b-8610-06de24ef529a">
<img width="197" alt="image" src="https://github.com/user-attachments/assets/1628ae9b-081e-458a-b11d-0fd7024b60f5">
如图所示，原先的一级菜单内容消失且变透明。

**Comment by Stapxs** [comment]
已知 bug，暂未找到原因
